### ISSUE TITLE
Broken during starting

### ISSUE THREAD

**Issue by maihao14** [iris-edu/pyweed#119]
I installed pyweed in my new mac OS. But it cannot start successfully as usual. It reported this:
`Traceback (most recent call last):
  File "/Users/hao/opt/anaconda3/envs/pyweed/bin/pyweed", line 11, in <module>
    sys.exit(launch())
  File "/Users/hao/opt/anaconda3/envs/pyweed/lib/python3.7/site-packages/pyweed/pyweed_launcher.py", line 98, in launch
    pyweed = get_pyweed()
  File "/Users/hao/opt/anaconda3/envs/pyweed/lib/python3.7/site-packages/pyweed/pyweed_launcher.py", line 78, in get_pyweed
    from pyweed.gui.PyWeedGUI import PyWeedGUI
  File "/Users/hao/opt/anaconda3/envs/pyweed/lib/python3.7/site-packages/pyweed/gui/PyWeedGUI.py", line 26, in <module>
    from pyweed.gui.MainWindow import MainWindow
  File "/Users/hao/opt/anaconda3/envs/pyweed/lib/python3.7/site-packages/pyweed/gui/MainWindow.py", line 21, in <module>
    from pyweed.gui.Seismap import Seismap
  File "/Users/hao/opt/anaconda3/envs/pyweed/lib/python3.7/site-packages/pyweed/gui/Seismap.py", line 19, in <module>
    from mpl_toolkits.basemap import Basemap
  File "/Users/hao/opt/anaconda3/envs/pyweed/lib/python3.7/site-packages/mpl_toolkits/basemap/__init__.py", line 50, in <module>
    from .proj import Proj
  File "/Users/hao/opt/anaconda3/envs/pyweed/lib/python3.7/site-packages/mpl_toolkits/basemap/proj.py", line 6, in <module>
    from matplotlib.cbook import dedent
ImportError: cannot import name 'dedent' from 'matplotlib.cbook' (/Users/hao/opt/anaconda3/envs/pyweed/lib/python3.7/site-packages/matplotlib/cbook/__init__.py)`

I don't know what's happening.

**Comment by adam-iris** [comment]
Can you check on your versions of matplotlib and basemap? I think this is an API that was removed in matplotlib v.3.

**Comment by evangelos1** [comment]
Apparently "dedent" does not exist in matplotlib 3.3.2 (the version that will be installed with the pyweed environment on macOS 10.15.7). To avoid this problem one has to downgrade to matplotlib 3.2.2 or earlier.

PS: The pyweed conda environment installed basemap 1.2.1.

**Comment by adam-iris** [comment]
Thanks for the details! I've added a note about this at https://iris-edu.github.io/pyweed/Support and I'm working on a new version to address this.

**Comment by evangelos1** [comment]
Cheers Adam.

By the way, I installed pyweed on a Windows 10 machine and didn't face any issues with matplotlib 3.3.2. However this installation came with basemap 1.2.2, unlike the macOS one that installed 1.2.1.

**Comment by adam-iris** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pyweed](https://trello.com/c/lOMzSubs/23-pyweed)
